# Stage 1: Build app
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copy project file and restore
COPY *.csproj .
RUN dotnet restore

# Copy all source and publish
COPY . .
RUN dotnet publish -c Release -o out

# Stage 2: Run app
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/out .

# Run the app
ENTRYPOINT ["dotnet", "TechNova.dll"]
